make T=best2300p_ibrt -j OTA_ENABLE=1 TWS_PROMPT_SYNC=1 MIX_AUDIO_PROMPT_WITH_A2DP_MEDIA_ENABLED=1 GEN_LIB=1
make T=best2300p_ibrt -j OTA_ENABLE=1 BLE=1 TWS_PROMPT_SYNC=1 MIX_AUDIO_PROMPT_WITH_A2DP_MEDIA_ENABLED=1 GEN_LIB=1
make T=best2300p_ibrt_anc -j OTA_ENABLE=1 TWS_PROMPT_SYNC=1 MIX_AUDIO_PROMPT_WITH_A2DP_MEDIA_ENABLED=1 GEN_LIB=1
make T=best2300p_ibrt_anc -j OTA_ENABLE=1 BLE=1 TWS_PROMPT_SYNC=1 MIX_AUDIO_PROMPT_WITH_A2DP_MEDIA_ENABLED=1 GEN_LIB=1


